# Generated by Django 4.2.4 on 2023-08-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipestep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipestep',
            old_name='instructions',
            new_name='instruction',
        ),
    ]
